---
name: github pages

on:
  push:
    branches:
      - main
      - 'lyz-code/blue-book'
  schedule:
    - cron: 11 06 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Number of commits to fetch. 0 indicates all history.
          # Default: 1
          fetch-depth: 0

      - name: Setup Python
        # https://github.com/actions/virtual-environments/issues/1202
        # uses: actions/setup-python@v1
        # with:
        #   python-version: '3.7'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          architecture: x64

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install pip-tools
        
      - name: Update requirements
        run: make update

      - name: Clone zettelkasten
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          #git clone https://github.com/omegakid1902/zettelkasten.git
          git submodule init
          git submodule update
          ls
          git status

      - name: Scan md file to publish
        run: python publish.py
        
      - name: Make the site
        run: make build-docs

      - uses: actions/checkout@v2
#      - name: Create report file
#        run: date +%s > report.txt
      - name: Commit report
        run: |
          cd zettelkasten
          git reset --hard
          cd ..
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt # git add docs/newsletter
          git add docs/
          git add zettelkasten/
          git diff-index --quiet HEAD \
            || git commit -m "gh-pages build number #${{ github.run_number }}"
          git tag gh-page-build.#${{ github.run_number }}
          git push origin gh-page-build.#${{ github.run_number }}
          git push origin main
          
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          #deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          allow_empty_commit: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
